# This run in the mattermost gitlab internal instance

variables:
  AWS_DEFAULT_REGION: us-east-1
  IMAGE_BUILD: cimg/go:1.19-node
  IMAGE_AWS_CI: $CI_REGISTRY/images/aws-ci:2.1.1-1

stages:
  - build
  - deploy

build-package:
  stage: build
  image: $IMAGE_BUILD
  before_script:
    - CGO_ENABLED=1 go install --tags extended github.com/gohugoio/hugo@v0.101.0
  script:
    - make dist
  artifacts:
    paths:
      - ./dist/html
    expire_in: 2 hours
  only:
    refs:
      - master

s3-release:
  image: $IMAGE_AWS_CI
  stage: deploy
  script:
    - aws s3 sync dist/html s3://mattermost-developer-documentation/branches/master --delete --cache-control no-cache --acl public-read --no-progress
  needs:
    - build-package
  only:
    refs:
      - master
