version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.12

jobs:
  build:
    docker:
      - image: circleci/golang:1.13-node
    steps:
      - checkout
      - run:
          name: build Hugo
          environment:
            HUGO_VERSION: 0.67.1
          command: |
            wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
            tar -xvf /tmp/hugo.tar.gz hugo
            sudo mv hugo /usr/bin/
      - run: make dist
      - persist_to_workspace:
          root: .
          paths:
            - dist/html

  status:
    docker:
      - image: circleci/python:3.6
    steps:
      - run:
          name: Reporting status to GitHub
          command: 'curl -H "Authorization: token $GITHUB_TOKEN" --data "{\"state\": \"success\", \"target_url\": \"http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/commits/<< pipeline.git.revision >>\", \"description\": \"Deployed to S3\", \"context\": \"Continuous Deployment\"}" "https://api.github.com/repos/mattermost/mattermost-developer-documentation/statuses/<< pipeline.git.revision >>"'

workflows:
  version: 2
  ci:
    jobs:
      - build
      - deploy:
          context: mattermost-dev-docs-s3
          requires:
            - build
      - status:
          context: matterbuild-github-token
          requires:
            - deploy
