name: notify-mm-blog
on:
  push:
    branches:
      - master
    paths:
      - 'site/content/blog/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - shell: bash
        run: |
          set -x
          git diff --name-only --diff-filter=A HEAD~1 -- 'site/content/blog/*.md' > file.log
          FILEADDED=$(cat file.log)
          echo $FILEADDED
          if [ -z "$FILEADDED" ]
          then
            echo "nothing added in the .md"
            echo "{}" > mattermost.json
            exit 0
          fi
          FILENAME=$(cat $FILEADDED | grep slug: | cut -d':' -f 2 | sed 's/^ *//g')
          TITLE=$(cat $FILEADDED | grep title: | cut -d':' -f 2 | sed 's/^ *//g')
          TITLE="${TITLE%\"'}" # remove suffix quote
          TITLE="${TITLE#\'"}" # remove prefix quote
          AUTHOR=$(cat $FILEADDED | grep author: | cut -d':' -f 2 | sed 's/^ *//g')
          AUTHOR_GH=$(cat $FILEADDED | grep github: | cut -d':' -f 2 | sed 's/^ *//g')
          echo "{\"username\":\"GitHub Action Notify\",\"icon_url\":\"https://www.mattermost.org/wp-content/uploads/2016/04/icon.png\",\"attachments\":[{\"author_name\":\"$AUTHOR\",\"author_link\":\"https://github.com/$AUTHOR_GH\",\"fallback\":\"New Blog Post! Check out [here](https://developers.mattermost.com/blog/)\",\"color\":\"good\",\"title\":\"$TITLE\",\"text\":\"New Blog Post! Check out [here](https://developers.mattermost.com/blog/$FILENAME)\"}]}" > mattermost.json

      - uses: mattermost/action-mattermost-notify@master
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}


